// libfile_redirect_hook.h — auto-generated by WinlatorDecompile
// Source: libfile_redirect_hook.so

#pragma once
#include <stdint.h>
#include <stdbool.h>

// Exported API
void _FINI_0(void);;
void entry(void);;
FILE * fopen(char *__filename,char *__modes);;
