// libfile_redirect_hook.c — auto-generated by WinlatorDecompile
// Source: libfile_redirect_hook.so

#include <stdint.h>
#include <stdbool.h>
#include "hook_impl.h"
#include "libfile_redirect_hook.h"


// ─────────────────────────────────────────────
// EXPORTED
// ─────────────────────────────────────────────

/* @00100614  size=8 */

void _FINI_0(void)

{
  FUN_0010060c();
  return;
}


/* @001005fc  size=16 */

void entry(void)

{
  __cxa_finalize(&PTR_LOOP_001016f0);
  return;
}


/* @00100660  size=44 */

FILE * fopen(char *__filename,char *__modes)

{
  FILE *pFVar1;
  
  pFVar1 = (FILE *)hook_fopen(__filename,__modes);
  return pFVar1;
}



// ─────────────────────────────────────────────
// INTERNAL
// ─────────────────────────────────────────────

/* @0010060c  size=8 */

void FUN_0010060c(void)

{
  return;
}


/* @0010061c  size=20 */

void FUN_0010061c(code *UNRECOVERED_JUMPTABLE)

{
  if (UNRECOVERED_JUMPTABLE != (code *)0x0) {
                    /* WARNING: Could not recover jumptable at 0x00100628. Too many branches */
                    /* WARNING: Treating indirect jump as call */
    (*UNRECOVERED_JUMPTABLE)();
    return;
  }
  return;
}


/* @00100630  size=32 */

void FUN_00100630(uint64_t param_1)

{
  __cxa_atexit(FUN_0010061c,param_1,&PTR_LOOP_001016f0);
  return;
}


/* @00100650  size=16 */

void FUN_00100650(void)

{
  __register_atfork();
  return;
}


/* @00100690  size=20 */

void FUN_00100690(void)

{
  (*(code *)(uint8_t *)0x0)();
  return;
}


