// libgsl_alloc_hook.c — auto-generated by WinlatorDecompile
// Source: libgsl_alloc_hook.so

#include <stdint.h>
#include <stdbool.h>
#include "hook_impl.h"
#include "libgsl_alloc_hook.h"


// ─────────────────────────────────────────────
// EXPORTED
// ─────────────────────────────────────────────

/* @0010073c  size=8 */

void _FINI_0(void)

{
  FUN_00100734();
  return;
}


/* @00100724  size=16 */

void entry(void)

{
  __cxa_finalize(&PTR_LOOP_00101890);
  return;
}


/* @00100788  size=56 */

void gsl_memory_alloc_pure(uint32_t param_1,uint32_t param_2,uint64_t param_3)

{
  hook_gsl_memory_alloc_pure_64(param_1,param_2,param_3);
  return;
}


/* @001007c0  size=52 */

void gsl_memory_alloc_pure_64(uint64_t param_1,uint32_t param_2,uint64_t param_3)

{
  hook_gsl_memory_alloc_pure_64(param_1,param_2,param_3);
  return;
}


/* @001007f4  size=36 */

void gsl_memory_free_pure(uint64_t param_1)

{
  hook_gsl_memory_free_pure(param_1);
  return;
}



// ─────────────────────────────────────────────
// INTERNAL
// ─────────────────────────────────────────────

/* @00100734  size=8 */

void FUN_00100734(void)

{
  return;
}


/* @00100744  size=20 */

void FUN_00100744(code *UNRECOVERED_JUMPTABLE)

{
  if (UNRECOVERED_JUMPTABLE != (code *)0x0) {
                    /* WARNING: Could not recover jumptable at 0x00100750. Too many branches */
                    /* WARNING: Treating indirect jump as call */
    (*UNRECOVERED_JUMPTABLE)();
    return;
  }
  return;
}


/* @00100758  size=32 */

void FUN_00100758(uint64_t param_1)

{
  __cxa_atexit(FUN_00100744,param_1,&PTR_LOOP_00101890);
  return;
}


/* @00100778  size=16 */

void FUN_00100778(void)

{
  __register_atfork();
  return;
}


/* @00100820  size=20 */

void FUN_00100820(void)

{
  (*(code *)(uint8_t *)0x0)();
  return;
}


