// libgsl_alloc_hook.h — auto-generated by WinlatorDecompile
// Source: libgsl_alloc_hook.so

#pragma once
#include <stdint.h>
#include <stdbool.h>

// Exported API
void _FINI_0(void);;
void entry(void);;
void gsl_memory_alloc_pure(uint32_t param_1,uint32_t param_2,uint64_t param_3);;
void gsl_memory_alloc_pure_64(uint64_t param_1,uint32_t param_2,uint64_t param_3);;
void gsl_memory_free_pure(uint64_t param_1);;
