// libmain_hook.h — auto-generated by WinlatorDecompile
// Source: libmain_hook.so

#pragma once
#include <stdint.h>
#include <stdbool.h>

// Exported API
void _FINI_0(void);;
void android_dlopen_ext(uint64_t param_1,uint32_t param_2,uint64_t param_3);;
void android_load_sphal_library(uint64_t param_1,uint32_t param_2);;
void entry(void);;
