// libmain_hook.c — auto-generated by WinlatorDecompile
// Source: libmain_hook.so

#include <stdint.h>
#include <stdbool.h>
#include "hook_impl.h"
#include "libmain_hook.h"


// ─────────────────────────────────────────────
// EXPORTED
// ─────────────────────────────────────────────

/* @001006d4  size=8 */

void _FINI_0(void)

{
  FUN_001006cc();
  return;
}


/* @00100720  size=52 */

void android_dlopen_ext(uint64_t param_1,uint32_t param_2,uint64_t param_3)

{
  hook_android_dlopen_ext(param_1,param_2,param_3);
  return;
}


/* @00100754  size=44 */

void android_load_sphal_library(uint64_t param_1,uint32_t param_2)

{
  hook_android_load_sphal_library(param_1,param_2);
  return;
}


/* @001006bc  size=16 */

void entry(void)

{
  __cxa_finalize(&PTR_LOOP_001017f0);
  return;
}



// ─────────────────────────────────────────────
// INTERNAL
// ─────────────────────────────────────────────

/* @001006cc  size=8 */

void FUN_001006cc(void)

{
  return;
}


/* @001006dc  size=20 */

void FUN_001006dc(code *UNRECOVERED_JUMPTABLE)

{
  if (UNRECOVERED_JUMPTABLE != (code *)0x0) {
                    /* WARNING: Could not recover jumptable at 0x001006e8. Too many branches */
                    /* WARNING: Treating indirect jump as call */
    (*UNRECOVERED_JUMPTABLE)();
    return;
  }
  return;
}


/* @001006f0  size=32 */

void FUN_001006f0(uint64_t param_1)

{
  __cxa_atexit(FUN_001006dc,param_1,&PTR_LOOP_001017f0);
  return;
}


/* @00100710  size=16 */

void FUN_00100710(void)

{
  __register_atfork();
  return;
}


/* @00100780  size=20 */

void FUN_00100780(void)

{
  (*(code *)(uint8_t *)0x0)();
  return;
}


